base_url = "https://spineki.github.io/introduction/"
compile_sass = true
title = "book theme"
description = "A book theme"
build_search_index = true

[markdown]
highlight_code = true

[extra]
book_number_chapters = true

[search]
index_format = "elasticlunr_json"